name: compact_dir
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  dropdown_search: ^5.0.6
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.1
  pdf: ^3.10.4
  printing: ^5.11.0  # Para generar y compartir PDFs fÃ¡cilmente
  open_file: ^3.3.2  # Para abrir el PDF generado
  shared_preferences: ^2.2.2
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imagenes/
    - assets/sounds/